### ISSUE TITLE
`plot_recruitment` cannot inherit params from itself

### ISSUE THREAD

**Issue by kellijohnson-NOAA** [nmfs-ost/satf#11]
The first two arguments of `plot_recruiment()` are not defined in the argument list for roxygen. Instead `@inheritParams plot_recruitment` is listed. This line should be removed and `dat` and `model` should be documented.
https://github.com/nmfs-ost/satf/blob/1641eba94dc762663725213503d450f984bec846/R/plot_recruitment.R#L3

**Comment by sbreitbart-NOAA** [comment]
Looks like this issue was resolved, so I'm going to close it. Please reopen if needed.
