### ISSUE TITLE
exp_all_figs_tables missing return

### ISSUE THREAD

**Issue by Schiano-NOAA** [nmfs-ost/satf#36]
The exp_all_figs_tables function is missing the return info. Is this intentional?

https://github.com/nmfs-ost/satf/blob/742c21241f16e4e24554f3a66e60dac3ea194676/R/exp_all_figs_tables.R#L12

**Comment by sbreitbart-NOAA** [comment]
The return info will be added upon merging the key-quantities branch: https://github.com/nmfs-ost/satf/pull/29/files#diff-5b3bb5539afa781170de0d59ed1a33692a944e619614643e2d7b0b9e6c52d10f
