### ISSUE TITLE
Create fxn to save all tables and figures

### ISSUE THREAD

**Issue by Schiano-NOAA** [nmfs-ost/satf#4]
Create a function that will produce all applicable tables and figures in the package similarly to r4ss summary html.

Unsure if we will be able to make it as a dashboard or shiny app like r4ss, but should be able to compile the tables (csv or image?) and figures (png) and save all into a folder

**Comment by sbreitbart-NOAA** [comment]
Confirming: was this issue repeated in this PR and therefore completed? https://github.com/nmfs-ost/satf/issues/21

**Comment by Schiano-NOAA** [comment]
@sbreitbart-NOAA I think so. We can revisit the dashboard thing at another time
